language: android
android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

script:
  - ./gradlew build assembleRelease
